AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

#
# Lint
#

Lint/HandleExceptions:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

#
# Layout
#

Layout/SpaceBeforeFirstArg:
  Enabled: false

#
# Metrics
#

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

#
# Naming
#

Naming/AccessorMethodName:
  Enabled: false

#
# Style
#

Style/ConditionalAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
