language: ruby
cache: bundler
bundler_args: --without development doc

before_install:
  - gem update --system
  - gem --version

rvm:
  - jruby-9.1.17.0
  - 2.2
  - 2.3
  - 2.4.3
  - 2.5.0

matrix:
  fast_finish: true

branches:
  only:
    - master
